---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secrets-job-config
  namespace: example
data:
  K8S_VERSION: "v1.25.8"
  entrypoint.sh: |
    #!/bin/sh
    set -euxo pipefail
    apk add --no-cache curl \
      && curl -LO "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl" \
      && mv kubectl /bin/kubectl \
      && chmod +x /bin/kubectl \
      && kubectl \
        -n ${K8S_NAMESPACE} \
        create secret generic gopher-squeeze-secret \
        --from-file WEBHOOK_SECRET=<(cat /dev/random \
          | head -c 4096 \
          | sha512sum \
          | head -c 128 \
          | xxd -r -p \
          | base64 \
          | sed 's/+//g;s/\///g;s/=//g' \
          | head -c 64 \
        ) \
      ;
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-job-serviceaccount
  namespace: example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secrets-job-role
  namespace: example
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-job-rolebinding
  namespace: example
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secrets-job-role
subjects:
  - kind: ServiceAccount
    name: secrets-job-serviceaccount
    namespace: example
---
apiVersion: batch/v1
kind: Job
metadata:
  name: secrets-job
  namespace: example
spec:
  template:
    spec:
      containers:
        - name: secrets-job-container
          image: alpine
          command: ["/bin/sh"]
          args: ["/opt/entrypoint.sh"]
          env:
            - name: K8S_VERSION
              valueFrom:
                 configMapKeyRef:
                   name: secrets-job-config
                   key: K8S_VERSION
            - name: K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              subPath: entrypoint.sh
              mountPath: /opt/entrypoint.sh
              readOnly: true
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: secrets-job-config
  backoffLimit: 0
